// Bot Builders — printable game-asset gallery.
// Cards use cost (credits), atk (damage), def (HP on bots).
window.ASSETS = [
  // ── Active Bots (primary attackers) ──────────────────────
  { id: '001', type: 'card', name: 'Striker', category: 'Active', cost: 3, atk: 4, def: 5,
    effect: 'Attack (1 AP): Deal 4 damage to target enemy bot.', flavor: 'Precision over power.', image: null },
  { id: '002', type: 'card', name: 'Brawler', category: 'Active', cost: 4, atk: 5, def: 6,
    effect: 'Attack (1 AP): Deal 5 damage to a bot or 3 to enemy base. Special (1 AP): +2 damage this turn.', flavor: 'Built for the front line.', image: null },
  { id: '003', type: 'card', name: 'Artillery', category: 'Active', cost: 5, atk: 7, def: 4,
    effect: 'Attack (1 AP): Deal 7 damage to a bot OR 4 to enemy base. Cannot target Defensive-position bots.', flavor: 'From a distance, with intent.', image: null },
  { id: '004', type: 'card', name: 'Commander', category: 'Active', cost: 4, atk: 3, def: 6,
    effect: 'Attack (1 AP): Deal 3 damage. Special (1 AP): Your Secondary Active deals +2 damage this turn.', flavor: 'Every squad needs a leader.', image: null },
  { id: '005', type: 'card', name: 'Saboteur', category: 'Active', cost: 3, atk: 3, def: 4,
    effect: 'Attack (1 AP): Deal 3 damage. Special (1 AP): Destroy one face-down trap an opponent controls.', flavor: 'Wires cut, plans ruined.', image: null },
  { id: '006', type: 'card', name: 'Assault Bot', category: 'Active', cost: 4, atk: 6, def: 5,
    effect: 'Attack (1 AP): Deal 6 damage to target enemy bot.', flavor: 'No subtlety. No mercy.', image: null },
  // ── Defensive Bots (bodyguards / interceptors) ───────────
  { id: '013', type: 'card', name: 'Bulwark', category: 'Defensive', cost: 3, atk: 0, def: 8,
    effect: 'Guard: Intercept all attacks targeting your base. Reflect 1 damage back to attacker.', flavor: 'Step behind me.', image: null },
  { id: '014', type: 'card', name: 'Fortress', category: 'Defensive', cost: 4, atk: 1, def: 10,
    effect: 'Guard: Intercept all attacks targeting your base. This bot does not reflect damage.', flavor: 'An immovable wall.', image: null },
  { id: '015', type: 'card', name: 'Spike Wall', category: 'Defensive', cost: 3, atk: 2, def: 6,
    effect: 'Guard: Intercept attacks. Reflect 2 damage on hit. After reflecting: -1 DEF permanently.', flavor: 'Touch it and bleed.', image: null },
  { id: '016', type: 'card', name: 'Shield Drone', category: 'Defensive', cost: 2, atk: 0, def: 7,
    effect: 'Guard: Intercept attacks targeting your base. Once per turn: prevent 2 damage from one attack.', flavor: 'Constant, quiet protection.', image: null },
  // ── Support Bots (healers / buffers) ─────────────────────
  { id: '017', type: 'card', name: 'Repair Bot', category: 'Support', cost: 2, atk: 0, def: 3,
    effect: 'Ability (1 AP): Restore 3 HP to target bot.', flavor: 'Welding torch at the ready.', image: null },
  { id: '018', type: 'card', name: 'Booster', category: 'Support', cost: 3, atk: 0, def: 2,
    effect: 'Ability (1 AP): Target Active or Secondary bot gains +2 ATK this turn.', flavor: 'Overclock and overdeliver.', image: null },
  { id: '019', type: 'card', name: 'Medic', category: 'Support', cost: 2, atk: 0, def: 4,
    effect: 'Ability (1 AP): Restore 5 HP to target bot. Once per turn.', flavor: 'Patch up and push on.', image: null },
  { id: '020', type: 'card', name: 'Overcharger', category: 'Support', cost: 3, atk: 0, def: 2,
    effect: 'Ability (1 AP): Target bot may attack twice this turn. Cannot use on consecutive turns.', flavor: 'Push the limit. Then push harder.', image: null },
  { id: '021', type: 'card', name: 'Shield Gen', category: 'Support', cost: 2, atk: 0, def: 3,
    effect: 'Ability (1 AP): Give target bot +3 DEF until your next turn.', flavor: 'A bubble of bad ideas for your enemies.', image: null },
  // ── Ability Cards: Instants (one-shot, your turn) ────────
  { id: '022', type: 'card', name: 'Scrap Bomb', category: 'Instant', cost: 1, atk: 3, def: 0,
    effect: 'Play (1 AP): Deal 3 damage to any target bot.', flavor: 'One bot\'s trash is another\'s ammunition.', image: null },
  { id: '023', type: 'card', name: 'Overdrive', category: 'Instant', cost: 1, atk: 0, def: 0,
    effect: 'Play (1 AP): One bot gains +3 ATK this turn.', flavor: 'Redline it.', image: null },
  { id: '024', type: 'card', name: 'Salvage', category: 'Instant', cost: 1, atk: 0, def: 0,
    effect: 'Play (1 AP): Draw 2 cards and gain 1 credit.', flavor: 'Find value in the wreckage.', image: null },
  { id: '025', type: 'card', name: 'Emergency Repair', category: 'Instant', cost: 2, atk: 0, def: 0,
    effect: 'Play (1 AP): Restore 4 HP to your base.', flavor: 'Duct tape and determination.', image: null },
  { id: '026', type: 'card', name: 'Hack', category: 'Instant', cost: 2, atk: 0, def: 0,
    effect: 'Play (1 AP): Take control of target enemy bot this turn. It cannot attack its owner.', flavor: 'I\'m in. Your move.', image: null },
  { id: '027', type: 'card', name: 'Power Surge', category: 'Instant', cost: 3, atk: 0, def: 0,
    effect: 'Play (1 AP): Gain 2 extra AP this turn (use immediately).', flavor: 'Caffeine for circuits.', image: null },
  { id: '028', type: 'card', name: 'Parts Scavenge', category: 'Instant', cost: 0, atk: 0, def: 0,
    effect: 'Play (1 AP): Gain 3 credits. (Costs 0 credits — you only spend the AP.)', flavor: 'Everything has a use.', image: null },
  { id: '029', type: 'card', name: 'EMP Blast', category: 'Instant', cost: 2, atk: 2, def: 0,
    effect: 'Play (1 AP): Deal 2 damage to all bots of one chosen position type (all players).', flavor: 'Lights out, everybody.', image: null },
  // ── Ability Cards: Traps (face-down, opponent turn) ──────
  { id: '030', type: 'card', name: 'Ambush', category: 'Trap', cost: 1, atk: 2, def: 0,
    effect: 'Trap: When an enemy bot attacks your base, deal 2 damage to it and negate 2 of the incoming damage.', flavor: 'They never see it coming.', image: null },
  { id: '031', type: 'card', name: 'Failsafe', category: 'Trap', cost: 1, atk: 0, def: 0,
    effect: 'Trap: When one of your bots would be destroyed, it survives with 1 HP instead. Then discard this.', flavor: 'One last backup routine.', image: null },
  { id: '032', type: 'card', name: 'Counter-Hack', category: 'Trap', cost: 2, atk: 0, def: 0,
    effect: 'Trap: When an enemy plays an Instant, negate it and gain 2 credits.', flavor: 'Nice try. My turn.', image: null },
  { id: '033', type: 'card', name: 'Tripwire', category: 'Trap', cost: 0, atk: 1, def: 0,
    effect: 'Trap: When an enemy plays a bot to any position, deal 1 damage to it.', flavor: 'Watch your step.', image: null },
  { id: '034', type: 'card', name: 'Signal Jam', category: 'Trap', cost: 1, atk: 0, def: 0,
    effect: 'Trap: When an enemy activates a bot\'s special ability, negate it.', flavor: 'No signal. No orders.', image: null },
  { id: '035', type: 'card', name: 'Retreat Order', category: 'Trap', cost: 1, atk: 0, def: 0,
    effect: 'Trap: When your bot would be destroyed, swap it to bench with 1 HP instead.', flavor: 'Live to fight another round.', image: null },
];
