// Bot Builders — printable game-asset gallery.
// Cards use cost (credits), atk (damage), def (HP on bots).
window.ASSETS = [
  // ── Active Bots (primary attackers) ──────────────────────
  { id: '001', type: 'card', name: 'Striker', category: 'Active', cost: 3, atk: 4, def: 5,
    effect: 'Attack (1 AP): Deal 4 damage to target enemy bot.', flavor: 'Precision over power.', image: null },
  { id: '002', type: 'card', name: 'Brawler', category: 'Active', cost: 4, atk: 5, def: 6,
    effect: 'Attack (1 AP): Deal 5 damage to a bot or 3 to enemy base. Special (1 AP): +2 damage this turn.', flavor: 'Built for the front line.', image: null },
  { id: '003', type: 'card', name: 'Artillery', category: 'Active', cost: 5, atk: 7, def: 4,
    effect: 'Attack (1 AP): Deal 7 damage to a bot OR 4 to enemy base.', flavor: 'From a distance, with intent.', image: null },
  { id: '004', type: 'card', name: 'Commander', category: 'Active', cost: 4, atk: 3, def: 6,
    effect: 'Attack (1 AP): Deal 3 damage. Special (1 AP): Your Secondary Active deals +2 damage this turn.', flavor: 'Every squad needs a leader.', image: null },
  { id: '005', type: 'card', name: 'Saboteur', category: 'Active', cost: 3, atk: 3, def: 4,
    effect: 'Attack (1 AP): Deal 3 damage. Special (1 AP): Destroy one face-down trap an opponent controls.', flavor: 'Wires cut, plans ruined.', image: null },
  { id: '006', type: 'card', name: 'Assault Bot', category: 'Active', cost: 4, atk: 6, def: 5,
    effect: 'Attack (1 AP): Deal 6 damage to target enemy bot.', flavor: 'No subtlety. No mercy.', image: null },
  { id: '007', type: 'card', name: 'Breacher', category: 'Active', cost: 4, atk: 3, def: 6,
    effect: 'Attack (1 AP): Deal 3 damage to target enemy bot or base. Ignores Defensive-position bots — attacks bypass them entirely.', flavor: 'Walls are just suggestions.', image: null },
  // ── Secondary Active Bots (flankers / debuffers) ─────────
  { id: '008', type: 'card', name: 'Scout', category: 'Secondary', cost: 2, atk: 2, def: 4,
    effect: 'Attack (1 AP): Deal 2 damage. On hit: target bot gets -1 ATK next turn.', flavor: 'Small, fast, annoying.', image: null },
  { id: '009', type: 'card', name: 'Disruptor', category: 'Secondary', cost: 3, atk: 3, def: 3,
    effect: 'Attack (1 AP): Deal 3 damage. On hit: target bot cannot use special abilities next turn.', flavor: 'Silence is a weapon.', image: null },
  { id: '010', type: 'card', name: 'Flanker', category: 'Secondary', cost: 2, atk: 3, def: 3,
    effect: 'Attack (1 AP): Deal 3 damage. If target has no adjacent ally bots, deal +2 instead.', flavor: 'Hit them where they\'re not looking.', image: null },
  { id: '011', type: 'card', name: 'Jammer', category: 'Secondary', cost: 2, atk: 1, def: 5,
    effect: 'Attack (1 AP): Deal 1 damage. On hit: enemy discards 1 random card from hand.', flavor: 'Interference on all channels.', image: null },
  { id: '012', type: 'card', name: 'Harasser', category: 'Secondary', cost: 3, atk: 4, def: 3,
    effect: 'Attack (1 AP): Deal 4 damage. On hit: target bot\'s ATK is halved (round down) next turn.', flavor: 'Death by a thousand pokes.', image: null },
  { id: '013', type: 'card', name: 'Scrambler', category: 'Secondary', cost: 2, atk: 2, def: 4,
    effect: 'Attack (1 AP): Deal 2 damage. On hit: swap target bot\'s ATK and DEF until end of next turn.', flavor: 'Turn their strength against them.', image: null },
  { id: '014', type: 'card', name: 'Displacer', category: 'Secondary', cost: 4, atk: 1, def: 4,
    effect: 'Attack (1 AP): Deal 1 damage. On hit: swap target enemy bot with a bot on opponent\'s bench — target is benched until your next turn.', flavor: 'Now you see it. Now you don\'t.', image: null },
  // ── Defensive Bots (bodyguards / interceptors) ───────────
  { id: '015', type: 'card', name: 'Bulwark', category: 'Defensive', cost: 3, atk: 0, def: 8,
    effect: 'Guard: Intercept all attacks targeting your base. Reflect 1 damage back to attacker.', flavor: 'Step behind me.', image: null },
  { id: '016', type: 'card', name: 'Fortress', category: 'Defensive', cost: 4, atk: 0, def: 10,
    effect: 'Guard: Intercept all attacks targeting your base. This bot does not reflect damage.', flavor: 'An immovable wall.', image: null },
  { id: '017', type: 'card', name: 'Spike Wall', category: 'Defensive', cost: 3, atk: 0, def: 6,
    effect: 'Guard: Intercept attacks. Reflect 2 damage on hit.', flavor: 'Touch it and bleed.', image: null },
  { id: '018', type: 'card', name: 'Shield Drone', category: 'Defensive', cost: 2, atk: 0, def: 7,
    effect: 'Guard: Intercept attacks targeting your base. Once per turn: prevent 2 damage from one attack.', flavor: 'Constant, quiet protection.', image: null },
  { id: '019', type: 'card', name: 'Nullifier', category: 'Defensive', cost: 3, atk: 0, def: 8,
    effect: 'Guard: Intercept half of incoming damage to your base (round down). When this bot is hit: the attacker deals 0 damage on its next attack.', flavor: 'No. And also: stop.', image: null },
  // ── Support Bots (healers / buffers) ─────────────────────
  { id: '020', type: 'card', name: 'Repair Bot', category: 'Support', cost: 2, atk: 0, def: 3,
    effect: 'Ability (1 AP): Restore 3 HP to target bot.', flavor: 'Welding torch at the ready.', image: null },
  { id: '021', type: 'card', name: 'Booster', category: 'Support', cost: 3, atk: 0, def: 2,
    effect: 'Ability (1 AP): Target Active or Secondary bot gains +2 ATK this turn.', flavor: 'Overclock and overdeliver.', image: null },
  { id: '022', type: 'card', name: 'Medic', category: 'Support', cost: 2, atk: 0, def: 4,
    effect: 'Ability (1 AP): Restore 5 HP to target bot. Once per turn.', flavor: 'Patch up and push on.', image: null },
  { id: '023', type: 'card', name: 'Overcharger', category: 'Support', cost: 3, atk: 0, def: 2,
    effect: 'Ability (1 AP): Target bot may attack twice this turn. Cannot use on consecutive turns.', flavor: 'Push the limit. Then push harder.', image: null },
  { id: '024', type: 'card', name: 'Shield Gen', category: 'Support', cost: 2, atk: 0, def: 3,
    effect: 'Ability (1 AP): Attacks against target bot deal -3 damage until your next turn.', flavor: 'A bubble of bad ideas for your enemies.', image: null },
  { id: '025', type: 'card', name: 'Bounty Drone', category: 'Support', cost: 3, atk: 0, def: 4,
    effect: 'Ability (1 AP): Target bot collects double credits when it defeats an enemy bot this turn (4 credits instead of 2).', flavor: 'Scrap is money, and money is more scrap.', image: null },
  // ── Ability Cards: Instants (one-shot, your turn) ────────
  { id: '026', type: 'card', name: 'Scrap Bomb', category: 'Instant', cost: 1, atk: 3, def: 0,
    effect: 'Play (1 AP): Deal 3 damage to any target bot.', flavor: 'One bot\'s trash is another\'s ammunition.', image: null },
  { id: '027', type: 'card', name: 'Overdrive', category: 'Instant', cost: 2, atk: 0, def: 0,
    effect: 'Play (1 AP): One bot gains +3 ATK this turn.', flavor: 'Redline it.', image: null },
  { id: '028', type: 'card', name: 'Salvage', category: 'Instant', cost: 1, atk: 0, def: 0,
    effect: 'Play (1 AP): Draw 2 cards and gain 1 credit.', flavor: 'Find value in the wreckage.', image: null },
  { id: '029', type: 'card', name: 'Emergency Repair', category: 'Instant', cost: 2, atk: 0, def: 0,
    effect: 'Play (1 AP): Restore 4 HP to your base.', flavor: 'Duct tape and determination.', image: null },
  { id: '030', type: 'card', name: 'Hack', category: 'Instant', cost: 2, atk: 0, def: 0,
    effect: 'Play (1 AP): Take control of target enemy bot this turn. It cannot attack its owner.', flavor: 'I\'m in. Your move.', image: null },
  { id: '031', type: 'card', name: 'Power Surge', category: 'Instant', cost: 3, atk: 0, def: 0,
    effect: 'Play (1 AP): Gain 2 extra AP this turn (use immediately).', flavor: 'Caffeine for circuits.', image: null },
  { id: '032', type: 'card', name: 'Parts Scavenge', category: 'Instant', cost: 1, atk: 0, def: 0,
    effect: 'Play (1 AP): Gain 3 credits.', flavor: 'Everything has a use.', image: null },
  { id: '033', type: 'card', name: 'EMP Blast', category: 'Instant', cost: 2, atk: 2, def: 0,
    effect: 'Play (1 AP): Deal 2 damage to up to 3 target bots.', flavor: 'Lights out, everybody.', image: null },
  { id: '034', type: 'card', name: 'System Shock', category: 'Instant', cost: 5, atk: 5, def: 0,
    effect: 'Play (1 AP): Target a damaged enemy bot. The next time it attacks or uses an ability, it is destroyed immediately.', flavor: 'Every circuit has a breaking point.', image: null },
  // ── Ability Cards: Traps (face-down, opponent turn) ──────
  { id: '035', type: 'card', name: 'Ambush', category: 'Trap', cost: 1, atk: 2, def: 0,
    effect: 'Trap: When an enemy bot attacks your base, deal 2 damage to it and negate 2 of the incoming damage.', flavor: 'They never see it coming.', image: null },
  { id: '036', type: 'card', name: 'Failsafe', category: 'Trap', cost: 1, atk: 0, def: 0,
    effect: 'Trap: When one of your bots would be destroyed, it survives with 1 HP instead. Then discard this.', flavor: 'One last backup routine.', image: null },
  { id: '037', type: 'card', name: 'Counter-Hack', category: 'Trap', cost: 2, atk: 0, def: 0,
    effect: 'Trap: When an enemy plays an Instant, negate it and gain 2 credits.', flavor: 'Nice try. My turn.', image: null },
  { id: '038', type: 'card', name: 'Tripwire', category: 'Trap', cost: 1, atk: 1, def: 0,
    effect: 'Trap: When an enemy plays a bot to any position, deal 1 damage to it.', flavor: 'Watch your step.', image: null },
  { id: '039', type: 'card', name: 'Signal Jam', category: 'Trap', cost: 1, atk: 0, def: 0,
    effect: 'Trap: When an enemy activates a bot\'s special ability, negate it.', flavor: 'No signal. No orders.', image: null },
  { id: '040', type: 'card', name: 'Retreat Order', category: 'Trap', cost: 1, atk: 0, def: 0,
    effect: 'Trap: When your bot would be destroyed, swap it to bench with 1 HP instead.', flavor: 'Live to fight another round.', image: null },
  // ── Workshop Tiles (optional base mods / play-area cards) ─
  { id: '201', type: 'tile', name: 'Workshop', category: 'Base Mod',
    effect: 'Once per turn: your first market purchase costs 1 fewer credit (minimum 0).', image: null },
  { id: '202', type: 'tile', name: 'Scrap Yard', category: 'Base Mod',
    effect: 'When any bot is destroyed: its controller gains +1 extra credit.', image: null },
  { id: '203', type: 'tile', name: 'Command Center', category: 'Base Mod',
    effect: 'Your first draw each turn costs 0 AP instead of 1.', image: null },
  // ── Printable Boards ──────────────────────────────────────
  { id: '204', type: 'tile', name: 'Game Board', category: 'Board',
    effect: 'Print one per player. Place bot cards on their matching slots. Track base HP with a die. Swap bench↔slot for 1 AP.', image: 'assets/images/game-board.svg' },
  { id: '205', type: 'tile', name: 'Bidding Board', category: 'Board',
    effect: 'Print one per table. Deal auction cards face-up in the pool. Each player gets a zone with chips and won-cards area. Bid 1 chip at a time.', image: 'assets/images/bidding-board.svg' },
];
