// Bot Builders — rulebook. Print-first: these rules print before the card gallery.
window.RULEBOOK = {
  theme: 'Bot Builders — You\'re an engineer commanding a squad of combat bots. Each bot is built for a specific tactical role: attackers, flankers, bodyguards, and healers. Assemble your lineup, manage your credits, and scrap the competition.',
  howToPlay: 'Setup: Auction-draft your starting squad (300 bidding chips, split evenly). Deploy up to 3 bots free, draw to 5 cards, start with 5 credits. Three market cards sit face-up; buy them with AP + credits. Earn +2 credits each time you scrap an enemy bot. When your personal deck runs out, shuffle your discard pile.',
  aTurn: 'You get 3 Action Points per turn (AP don\'t carry over). Spend them on: Draw (1 AP from your deck) · Buy from market (1 AP + credit cost) · Play a bot to a position (1 AP, 1 bot per slot) · Play an ability card (1 AP, Instants fire now, Traps are set face-down) · Attack with a bot (1 AP — fixed damage, no dice) · Activate a bot\'s special ability (1 AP) · Swap a position bot with a bench bot (1 AP). Damage is 1:1 (ATK 3 = 3 damage). Damage to bots persists — track with counters.',
  winCondition: 'Each player\'s base has 20 HP. When your base hits 0, you\'re eliminated. The player who deals the final hit scavenges 1 bot of their choice from the eliminated player\'s board (any position or bench) onto their own bench or into their hand. Last player with a standing base wins.',
  pieces: '5 piece types across 2 families — CARDS (35): Active Bots (primary attackers, some have special abilities), Secondary Bots (flankers that debuff), Defensive Bots (high-HP bodyguards that intercept and reflect), Support Bots (healers and buffers for Active/Secondary), Instants (one-shot effects played on your turn), Traps (set face-down, trigger on opponent actions). Workshop TILES (3): optional base mods you can buy. The BENCH is a storage zone — up to 6 bots of any type can sit here as backups (1 AP to swap a bench bot into a position). Plus: combat credits and a shared market deck.',
  ranges: 'Credits: cards cost 1–5. Active Bots: ATK 3–7, HP 4–8. Secondary Bots: ATK 1–4, HP 3–6. Defensive Bots: ATK 0, HP 6–10. Support Bots: ATK 0, HP 2–5. Ability cards: cost 1–3. Board limit: 1 bot per position (Active, Secondary, Defensive, Support), up to 6 on bench. Hand: unlimited one-shot ability cards.',
};
